name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        export POETRY_HOME=/opt/poetry
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.5.1
        $POETRY_HOME/bin/poetry install 

    - name: Run tests in tests/ with pytest
      run: |
        export POETRY_HOME=/opt/poetry
        $POETRY_HOME/bin/poetry run pytest --exitfirst --verbose --failed-first